<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace Doubles\Api\ViewModels\Organization;

use OC\Api\ViewModels\Organization\Impl\OrganizationViewModelListItemImpl;
use Doubles\BusinessRules\Responders\Organization\OrganizationListItemResponseStub1;

class OrganizationViewModelListItemStub1 extends OrganizationViewModelListItemImpl
{
    public const CREATED_AT = OrganizationListItemResponseStub1::CREATED_AT;

    public const DESCRIPTION = OrganizationListItemResponseStub1::DESCRIPTION;

    public const ID = OrganizationListItemResponseStub1::ID;

    public const LOGO = OrganizationListItemResponseStub1::LOGO;

    public const NAME = OrganizationListItemResponseStub1::NAME;

    public const UPDATED_AT = OrganizationListItemResponseStub1::UPDATED_AT;


    /**
     * {@inheritdoc}
     */
    public $description = self::DESCRIPTION;

    /**
     * {@inheritdoc}
     */
    public $id = self::ID;

    /**
     * {@inheritdoc}
     */
    public $logo = self::LOGO;
    /**
     * {@inheritdoc}
     */
    public $name = self::NAME;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable(self::CREATED_AT);
        $this->updatedAt = new \DateTimeImmutable(self::UPDATED_AT);
    }
}
