<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace Doubles\Api\ViewModels\Organization;

use OC\Api\ViewModels\Organization\Impl\OrganizationViewModelDetailImpl;
use Doubles\BusinessRules\Responders\Organization\OrganizationDetailResponseStub1;

class OrganizationViewModelDetailStub1 extends OrganizationViewModelDetailImpl
{
    public const CREATED_AT = OrganizationDetailResponseStub1::CREATED_AT;

    public const DESCRIPTION = OrganizationDetailResponseStub1::DESCRIPTION;

    public const ID = OrganizationDetailResponseStub1::ID;

    public const LOGO = OrganizationDetailResponseStub1::LOGO;

    public const NAME = OrganizationDetailResponseStub1::NAME;

    public const UPDATED_AT = OrganizationDetailResponseStub1::UPDATED_AT;


    /**
     * {@inheritdoc}
     */
    public $description = self::DESCRIPTION;

    /**
     * {@inheritdoc}
     */
    public $id = self::ID;

    /**
     * {@inheritdoc}
     */
    public $logo = self::LOGO;
    /**
     * {@inheritdoc}
     */
    public $name = self::NAME;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable(self::CREATED_AT);
        $this->updatedAt = new \DateTimeImmutable(self::UPDATED_AT);
    }
}
