<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace Doubles\Api\ViewModels\Organization;

use OC\Api\ViewModels\Organization\OrganizationViewModelDetail;
use PHPUnit\Framework\Assert;

trait OrganizationViewModelDetailTestCase
{
    use OrganizationViewModelTestCase;

    private function assertOrganizationViewModelDetail(OrganizationViewModelDetail $expected, OrganizationViewModelDetail $actual): void
    {
        $this->assertOrganizationViewModel($expected, $actual);
    }
}
