<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Domain\SubDomain;

use OC\BusinessRules\Requestors\Domain\SubDomain\DefaultNameRequest;
use OpenClassrooms\UseCase\Application\Annotations\Security;
use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCase;
use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

class DefaultName implements UseCase
{
    /**
     * @Security(roles="")
     *
     * @param DefaultNameRequest $useCaseRequest
     */
    public function execute(UseCaseRequest $useCaseRequest)
    {
        // TODO: Implement execute() method.
    }
}
