<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace Api\ViewModels\Organization\Impl;

use OC\Api\ViewModels\Organization\OrganizationViewModelDetailAssembler;
use OC\Api\ViewModels\Organization\Impl\OrganizationViewModelDetailAssemblerImpl;
use Doubles\Api\ViewModels\Organization\OrganizationViewModelDetailStub1;
use Doubles\Api\ViewModels\Organization\OrganizationViewModelDetailTestCase;
use Doubles\BusinessRules\Responders\Organization\OrganizationDetailResponseStub1;
use PHPUnit\Framework\TestCase;

class OrganizationViewModelDetailAssemblerImplTest extends TestCase
{
    use OrganizationViewModelDetailTestCase;

    /**
     * @var OrganizationViewModelDetailAssembler
     */
    private $assembler;

    /**
     * @test
     */
    final public function onCreateShouldReturnViewModel(): void
    {
        $actual = $this->assembler->create(new OrganizationDetailResponseStub1());
        $expected = new OrganizationViewModelDetailStub1();
        $this->assertOrganizationViewModelDetail($expected, $actual);
    }

    protected function setUp(): void
    {
        $this->assembler = new OrganizationViewModelDetailAssemblerImpl();
    }
}
