<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Request;

use OC\BusinessRules\Requestors\Organization\CreateOrganizationRequest;
use OC\BusinessRules\UseCases\CreateRequestTrait;

final class CreateOrganizationRequestDTO implements CreateOrganizationRequest
{
    use OrganizationCommonRequest;
    use CreateRequestTrait;
}
