<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Request;

use OC\BusinessRules\Requestors\Organization\DeleteOrganizationRequest;

final class DeleteOrganizationRequestDTO implements DeleteOrganizationRequest
{
    /**
     * @var int
     */
    public $organizationId;

    public function __construct(int $id)
    {
        $this->organizationId = $id;
    }

    public function getOrganizationId(): int
    {
        return $this->organizationId;
    }
}
