<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Request;

use OC\BusinessRules\Requestors\Organization\DeleteOrganizationRequest;
use OC\BusinessRules\Requestors\Organization\DeleteOrganizationRequestBuilder;

class DeleteOrganizationRequestBuilderImpl implements DeleteOrganizationRequestBuilder
{
    /**
     * @var int
     */
    private $organizationId;

    public function build(): DeleteOrganizationRequest
    {
        return new DeleteOrganizationRequestDTO($this->organizationId);
    }

    public function create(): DeleteOrganizationRequestBuilder
    {
        return $this;
    }

    public function withOrganizationId(int $id): DeleteOrganizationRequestBuilder
    {
        $this->organizationId = $id;

        return $this;
    }
}
