<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Request;

use OC\BusinessRules\Requestors\Organization\EditOrganizationRequest;

final class EditOrganizationRequestDTO implements EditOrganizationRequest
{
    use OrganizationCommonRequest;

    /**
     * @var bool
     */
    public $descriptionUpdated = false;

    /**
     * @var bool
     */
    public $logoUpdated = false;

    /**
     * @var bool
     */
    public $nameUpdated = false;

    /**
     * @var int
     */
    public $organizationId;

    public function getOrganizationId(): int
    {
        return $this->organizationId;
    }

    public function isDescriptionUpdated(): bool
    {
        return $this->descriptionUpdated;
    }

    public function isLogoUpdated(): bool
    {
        return $this->logoUpdated;
    }

    public function isNameUpdated(): bool
    {
        return $this->nameUpdated;
    }
}
