<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Request;

use OC\BusinessRules\Requestors\Organization\EditOrganizationRequest;
use OC\BusinessRules\Requestors\Organization\EditOrganizationRequestBuilder;

class EditOrganizationRequestBuilderImpl implements EditOrganizationRequestBuilder
{
    /**
     * @var EditOrganizationRequestDTO
     */
    private $request;

    public function build(): EditOrganizationRequest
    {
        return $this->request;
    }

    public function create(): EditOrganizationRequestBuilder
    {
        $this->request = new EditOrganizationRequestDTO();

        return $this;
    }

    public function withDescription(string $description): EditOrganizationRequestBuilder
    {
        $this->request->description = $description;
        $this->request->descriptionUpdated = true;

        return $this;
    }

    public function withLogo(string $logo): EditOrganizationRequestBuilder
    {
        $this->request->logo = $logo;
        $this->request->logoUpdated = true;

        return $this;
    }

    public function withName(string $name): EditOrganizationRequestBuilder
    {
        $this->request->name = $name;
        $this->request->nameUpdated = true;

        return $this;
    }

    public function withOrganizationId(int $id): EditOrganizationRequestBuilder
    {
        $this->request->organizationId = $id;

        return $this;
    }
}
