<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Request;

use OC\BusinessRules\Requestors\Organization\GetOrganizationsRequest;
use OC\BusinessRules\Requestors\Organization\GetOrganizationsRequestBuilder;

class GetOrganizationsRequestBuilderImpl implements GetOrganizationsRequestBuilder
{
    public function build(): GetOrganizationsRequest
    {
        return $this->request;
    }

    /**
     * @var GetOrganizationsRequestDTO
     */
    private $request;

    public function create(): GetOrganizationsRequestBuilder
    {
        $this->request = new GetOrganizationsRequestDTO();

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function withFilters(array $filters = []): GetOrganizationsRequestBuilder
    {
        $this->request->filters = $filters;

        return $this;
    }

    public function withItemsPerPage(int $itemsPerPage): GetOrganizationsRequestBuilder
    {
        $this->request->itemsPerPage = $itemsPerPage;

        return $this;
    }

    public function withPage(int $page = 1): GetOrganizationsRequestBuilder
    {
        $this->request->page = $page;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function withSort(array $sort = []): GetOrganizationsRequestBuilder
    {
        $this->request->sorts = $sort;

        return $this;
    }
}
