<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Request;

use OC\BusinessRules\Requestors\Organization\GetOrganizationRequest;
use OC\BusinessRules\Requestors\Organization\GetOrganizationRequestBuilder;

class GetOrganizationRequestBuilderImpl implements GetOrganizationRequestBuilder
{
    /**
     * @var GetOrganizationRequestDTO
     */
    private $request;

    public function create(): GetOrganizationRequestBuilder
    {
        $this->request = new GetOrganizationRequestDTO();

        return $this;
    }

    public function withOrganizationId(int $id): GetOrganizationRequestBuilder
    {
        $this->request->id = $id;

        return $this;
    }

    public function build(): GetOrganizationRequest
    {
        return $this->request;
    }
}
