<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Request;

use OC\BusinessRules\Requestors\Organization\GetOrganizationRequest;

final class GetOrganizationRequestDTO implements GetOrganizationRequest
{
    /**
     * @var int
     */
    public $id;

    public function getOrganizationId(): int
    {
        return $this->id;
    }
}
