<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\Api\Models\Organization;

class PatchOrganizationModel
{
    use OrganizationModelTrait;

    protected const DESCRIPTION_API_FIELD_NAME = 'description';

    protected const LOGO_API_FIELD_NAME = 'logo';

    protected const NAME_API_FIELD_NAME = 'name';

    /**
     * @var bool
     */
    public $descriptionUpdated = false;

    /**
     * @var bool
     */
    public $logoUpdated = false;

    /**
     * @var bool
     */
    public $nameUpdated = false;

    protected function build(array $data)
    {
        if (array_key_exists(self::DESCRIPTION_API_FIELD_NAME, $data)) {
            $this->description = $data[self::DESCRIPTION_API_FIELD_NAME];
            $this->descriptionUpdated = true;
        }

        if (array_key_exists(self::LOGO_API_FIELD_NAME, $data)) {
            $this->logo = $data[self::LOGO_API_FIELD_NAME];
            $this->logoUpdated = true;
        }

        if (array_key_exists(self::NAME_API_FIELD_NAME, $data)) {
            $this->name = $data[self::NAME_API_FIELD_NAME];
            $this->nameUpdated = true;
        }
    }
}
