<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\App\Entity\Organization;

use OC\BusinessRules\Entities\Organization\Organization;
use OC\BusinessRules\Entities\Organization\OrganizationFactory;

class OrganizationFactoryImpl implements OrganizationFactory
{
    public function create(): Organization
    {
        return new OrganizationImpl();
    }
}
