<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\App\Entity\Organization;

use OC\BusinessRules\Entities\Organization\Organization;

class OrganizationImpl extends Organization
{
}
