<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases;

trait CreateRequestTrait
{
    public function __call($name, $arguments)
    {
        if (preg_match('/is(.+)Updated/', $name)) {
            return true;
        }
    }
}
