<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Domain\SubDomain\DTO\Request;

use OC\BusinessRules\Requestors\Domain\SubDomain\DefaultNameRequest;

class DefaultNameRequestDTO implements DefaultNameRequest
{
}
