<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\Api\ViewModels\Organization\Impl;

use OC\Api\ViewModels\Organization\OrganizationViewModelDetail;

class OrganizationViewModelDetailImpl extends OrganizationViewModelDetail
{
}
