<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\Api\ViewModels\Organization\Impl;

use OC\Api\ViewModels\Organization\OrganizationViewModelAssemblerTrait;
use OC\Api\ViewModels\Organization\OrganizationViewModelDetail;
use OC\Api\ViewModels\Organization\OrganizationViewModelDetailAssembler;
use OC\BusinessRules\Responders\Organization\OrganizationDetailResponse;

class OrganizationViewModelDetailAssemblerImpl implements OrganizationViewModelDetailAssembler
{
    use OrganizationViewModelAssemblerTrait;

    public function create(OrganizationDetailResponse $organizationDetailResponse): OrganizationViewModelDetail
    {
        $vm = new OrganizationViewModelDetailImpl();
        $this->hydrateCommonFields($vm, $organizationDetailResponse);

        return $vm;
    }
}
