<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace Doubles\BusinessRules\Responders\Organization;

use OC\BusinessRules\Responders\Organization\OrganizationResponse;
use PHPUnit\Framework\Assert;

trait OrganizationResponseTestCase
{
    private function assertOrganizationResponse(
        OrganizationResponse $expected,
        OrganizationResponse $actual
    ): void {
        Assert::assertEquals($expected->getCreatedAt(), $actual->getCreatedAt());
        Assert::assertSame($expected->getDescription(), $actual->getDescription());
        Assert::assertSame($expected->getId(), $actual->getId());
        Assert::assertSame($expected->getLogo(), $actual->getLogo());
        Assert::assertSame($expected->getName(), $actual->getName());
        Assert::assertEquals($expected->getUpdatedAt(), $actual->getUpdatedAt());
    }
}
