<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace Doubles\BusinessRules\Responders\Organization;

use OC\BusinessRules\UseCases\Organization\DTO\Response\OrganizationDetailResponseAssemblerImpl;

class OrganizationDetailResponseAssemblerMock extends OrganizationDetailResponseAssemblerImpl
{
}
