<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization;

use OC\BusinessRules\Entities\Organization\Organization;
use OC\BusinessRules\Entities\Organization\OrganizationFactory;
use OC\BusinessRules\Gateways\Organization\OrganizationGateway;
use OC\BusinessRules\Requestors\Organization\CreateOrganizationRequest;
use OC\BusinessRules\Responders\Organization\OrganizationDetailResponse;
use OC\BusinessRules\Responders\Organization\OrganizationDetailResponseAssembler;
use OpenClassrooms\UseCase\Application\Annotations\Security;
use OpenClassrooms\UseCase\Application\Annotations\Transaction;
use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCase;
use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

class CreateOrganization implements UseCase
{
    use OrganizationCommonHydratorTrait;

    /**
     * @var OrganizationFactory
     */
    private $organizationFactory;

    /**
     * @var OrganizationGateway
     */
    private $organizationGateway;

    /**
     * @var OrganizationDetailResponseAssembler
     */
    private $organizationDetailResponseAssembler;

    public function __construct(
        OrganizationDetailResponseAssembler $organizationDetailResponseAssembler,
        OrganizationFactory $organizationFactory,
        OrganizationGateway $organizationGateway
    ) {
        $this->organizationFactory = $organizationFactory;
        $this->organizationGateway = $organizationGateway;
        $this->organizationDetailResponseAssembler = $organizationDetailResponseAssembler;
    }

    /**
     * @Transaction
     * @Security(roles="")
     *
     * @param CreateOrganizationRequest $useCaseRequest
     */
    public function execute(UseCaseRequest $useCaseRequest): OrganizationDetailResponse
    {
        $organization = $this->create();
        $this->populateFromRequest($organization, $useCaseRequest);
        $this->save($organization);

        return $this->createResponse($organization);
    }

    private function create(): Organization
    {
        return $this->organizationFactory->create();
    }

    private function save(Organization $organization): void
    {
        $this->organizationGateway->insert($organization);
    }

    private function createResponse(Organization $organization): OrganizationDetailResponse
    {
        return $this->organizationDetailResponseAssembler->create($organization);
    }
}
