<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization;

use OC\BusinessRules\Entities\Organization\Organization;
use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

trait OrganizationCommonHydratorTrait
{
    protected function populateFromRequest(Organization $organization, UseCaseRequest $request): void
    {
        !$request->isDescriptionUpdated() ?: $organization->setDescription($request->getDescription());
        !$request->isLogoUpdated() ?: $organization->setLogo($request->getLogo());
        !$request->isNameUpdated() ?: $organization->setName($request->getName());
    }
}
