<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace BusinessRules\UseCases\Domain\SubDomain;

use OC\BusinessRules\Requestors\Domain\SubDomain\DefaultNameRequest;
use OC\BusinessRules\UseCases\Domain\SubDomain\DTO\Request\DefaultNameRequestBuilderImpl;
use OC\BusinessRules\UseCases\Domain\SubDomain\DTO\Request\DefaultNameRequestDTO;
use OC\BusinessRules\UseCases\Domain\SubDomain\DefaultName;
use PHPUnit\Framework\TestCase;

class DefaultNameTest extends TestCase
{
    /**
     * @var DefaultNameRequestDTO
     */
    private $request;

    /**
     * @var DefaultName
     */
    private $useCase;

    /**
     * @test
     */
    final public function defaultNameReturnResponse(): void
    {
        $this->fail("TODO: Implement this test");
    }

    /**
     * @inheritdoc
     */
    protected function setUp(): void
    {
        $this->request = $this->buildRequest();
        $this->useCase = new DefaultName();
    }

    private function buildRequest(): DefaultNameRequest
    {
        return (new DefaultNameRequestBuilderImpl())
            ->create()
            ->build();
    }
}
