<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Entities\Organization;

interface OrganizationFactory
{
    public function create(): Organization;
}
