<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Requestors\Organization;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

interface CreateOrganizationRequestBuilder extends UseCaseRequest
{
    public function build(): CreateOrganizationRequest;

    public function create(): CreateOrganizationRequestBuilder;

    public function withDescription(string $description): CreateOrganizationRequestBuilder;

    public function withLogo(string $logo): CreateOrganizationRequestBuilder;

    public function withName(string $name): CreateOrganizationRequestBuilder;
}
