<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Requestors\Organization;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

interface CreateOrganizationRequest extends UseCaseRequest
{
    public function getDescription(): string;

    public function getLogo(): string;

    public function getName(): string;
}
