<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Requestors\Organization;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

interface DeleteOrganizationRequestBuilder extends UseCaseRequest
{
    public function build(): DeleteOrganizationRequest;

    public function create(): DeleteOrganizationRequestBuilder;

    public function withOrganizationId(int $id): DeleteOrganizationRequestBuilder;
}
