<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Requestors\Organization;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

interface EditOrganizationRequestBuilder extends UseCaseRequest
{
    public function build(): EditOrganizationRequest;

    public function create(): EditOrganizationRequestBuilder;

    public function withDescription(string $description): EditOrganizationRequestBuilder;

    public function withLogo(string $logo): EditOrganizationRequestBuilder;

    public function withName(string $name): EditOrganizationRequestBuilder;

    public function withOrganizationId(int $id): EditOrganizationRequestBuilder;
}
