<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Requestors\Organization;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

interface GetOrganizationsRequestBuilder extends UseCaseRequest
{
    public function create(): GetOrganizationsRequestBuilder;

    public function withFilters(array $filters = []): GetOrganizationsRequestBuilder;

    public function withItemsPerPage(int $itemsPerPage): GetOrganizationsRequestBuilder;

    public function withPage(int $page = 1): GetOrganizationsRequestBuilder;

    public function withSort(array $sort = []): GetOrganizationsRequestBuilder;

    public function build(): GetOrganizationsRequest;
}
