<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Requestors\Organization;

use OpenClassrooms\UseCase\BusinessRules\Requestors\UseCaseRequest;

interface GetOrganizationRequestBuilder extends UseCaseRequest
{
    public function create(): GetOrganizationRequestBuilder;

    public function withOrganizationId(int $id): GetOrganizationRequestBuilder;

    public function build(): GetOrganizationRequest;
}
