<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace Doubles\BusinessRules\Entities\Organization;

use OC\App\Entity\Organization\OrganizationImpl;

class OrganizationStub1 extends OrganizationImpl
{
    const CREATED_AT = '2020-04-01 08:26:47';

    const DESCRIPTION = 'Organization Stub 1 description';

    const ID = 234988;

    const LOGO = 'Organization Stub 1 logo';

    const NAME = 'Organization Stub 1 name';

    const UPDATED_AT = '2020-04-01 08:26:47';

    protected $description = self::DESCRIPTION;

    protected $id = self::ID;

    protected $logo = self::LOGO;

    protected $name = self::NAME;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable(self::CREATED_AT);
        $this->updatedAt = new \DateTimeImmutable(self::UPDATED_AT);
    }
}
