<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Response;

use OC\BusinessRules\Responders\Organization\OrganizationListItemResponse;

class OrganizationListItemResponseDTO implements OrganizationListItemResponse
{
    use OrganizationResponseCommonFieldTrait;
}
