<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Response;

use OC\BusinessRules\Responders\Organization\OrganizationDetailResponse;

class OrganizationDetailResponseDTO implements OrganizationDetailResponse
{
    use OrganizationResponseCommonFieldTrait;


}
