<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Response;

use OC\BusinessRules\Entities\Organization\Organization;
use OC\BusinessRules\Responders\Organization\OrganizationResponse;

trait OrganizationResponseAssemblerTrait
{
    private function hydrateCommonFields(Organization $entity, OrganizationResponse $response): OrganizationResponse
    {
        $response->createdAt = $entity->getCreatedAt();
        $response->description = $entity->getDescription();
        $response->id = $entity->getId();
        $response->logo = $entity->getLogo();
        $response->name = $entity->getName();
        $response->updatedAt = $entity->getUpdatedAt();

        return $response;
    }
}
