<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\UseCases\Organization\DTO\Response;

use OC\BusinessRules\Entities\Organization\Organization;
use OC\BusinessRules\Responders\Organization\OrganizationDetailResponse;
use OC\BusinessRules\Responders\Organization\OrganizationDetailResponseAssembler;

class OrganizationDetailResponseAssemblerImpl implements OrganizationDetailResponseAssembler
{
    use OrganizationResponseAssemblerTrait;

    public function create(Organization $entity): OrganizationDetailResponse
    {
        $response = new OrganizationDetailResponseDTO();

        $this->hydrateCommonFields($entity, $response);

        return $response;
    }
}
