<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Responders\Organization;

interface OrganizationDetailResponse extends OrganizationResponse
{
}
