<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Responders\Organization;

use OC\BusinessRules\Responders\PaginatedUseCaseResponse;
use OpenClassrooms\UseCase\BusinessRules\Entities\PaginatedCollection;

interface OrganizationListItemResponseAssembler
{
    public function createPaginatedCollection(PaginatedCollection $collection): PaginatedUseCaseResponse;
}
