<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Responders\Organization;

use OC\BusinessRules\Entities\Organization\Organization;

interface OrganizationDetailResponseAssembler
{
    public function create(Organization $entity): OrganizationDetailResponse;
}
