<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Responders\Organization;

use OC\BusinessRules\Responders\UseCaseResponse;

interface OrganizationResponse extends UseCaseResponse
{
    /**
     * @return \DateTimeImmutable
     */
    public function getCreatedAt(): \DateTimeImmutable;

    /**
     * @return string
     */
    public function getDescription(): string;

    /**
     * @return int
     */
    public function getId(): int;

    /**
     * @return string
     */
    public function getLogo(): string;

    /**
     * @return string
     */
    public function getName(): string;

    /**
     * @return \DateTimeImmutable
     */
    public function getUpdatedAt(): \DateTimeImmutable;
}
