<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\BusinessRules\Gateways\Organization;

use OC\BusinessRules\Entities\Organization\Organization;
use OC\BusinessRules\Gateways\Organization\Exceptions\OrganizationNotFoundException;
use OpenClassrooms\UseCase\BusinessRules\Entities\PaginatedCollection;

interface OrganizationGateway
{
    public function delete(Organization $organization): void;

    /**
     * @return PaginatedCollection|Organization[]
     */
    public function findAll(array $filters = [], array $sorts = [], array $pagination = []): iterable;

    /**
     * @throws OrganizationNotFoundException
     */
    public function findById(int $organizationId): Organization;

    public function insert(Organization $organization): void;

    public function update(Organization $organization): void;
}
