<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\Api\ViewModels\Organization;

use OC\BusinessRules\Responders\Organization\OrganizationListItemResponse;

interface OrganizationViewModelListItemAssembler
{
    /**
     * @param OrganizationListItemResponse[] $organizations
     *
     * @return OrganizationViewModelListItem[]
     */
    public function createListItems(array $organizations): array;
}
