<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\Api\ViewModels\Organization;

abstract class OrganizationViewModelListItem extends OrganizationViewModel
{
}
