<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\Api\ViewModels\Organization;

use OC\BusinessRules\Responders\Organization\OrganizationResponse;

trait OrganizationViewModelAssemblerTrait
{
    private function hydrateCommonFields(OrganizationViewModel $vm, OrganizationResponse $organization): void
    {
        $vm->createdAt = $organization->getCreatedAt();
        $vm->description = $organization->getDescription();
        $vm->id = $organization->getId();
        $vm->logo = $organization->getLogo();
        $vm->name = $organization->getName();
        $vm->updatedAt = $organization->getUpdatedAt();
    }
}
