<?php

// Auto Generated by OpenClassrooms Code Generator

declare(strict_types=1);

namespace OC\Api\ViewModels\Organization;

use OC\BusinessRules\Responders\Organization\OrganizationDetailResponse;

interface OrganizationViewModelDetailAssembler
{
    public function create(OrganizationDetailResponse $organizationDetailResponse): OrganizationViewModelDetail;
}
